sudo: required

language: java

jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - pwd
  - ls
  - chmod +x mvnw
#  - chmod +x ./deployment/deploy.sh

install: true

#script: "cp .travis.settings.xml $HOME/.m2/settings.xml && ./mvnw clean package -U"

script: "./mvnw clean package -U"

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: "bash deploy.sh"
#    on:
#      tags: true



